<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VariantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $variants = [
            [
                'product_id' => 1,
                'sku' => 'MBP14-M3-8-512',
                'processor' => 'Apple M3 Pro',
                'ram' => '8GB',
                'storage' => '512GB SSD',
                'graphics_card' => 'M3 Pro 14-core GPU',
                'display_size' => '14.2"',
                'resolution' => '3024x1964',
                'stock' => 10,
                'price' => 1999.00,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'product_id' => 1,
                'sku' => 'MBP14-M3-16-1TB',
                'processor' => 'Apple M3 Pro',
                'ram' => '16GB',
                'storage' => '1TB SSD',
                'graphics_card' => 'M3 Pro 18-core GPU',
                'display_size' => '14.2"',
                'resolution' => '3024x1964',
                'stock' => 8,
                'price' => 2499.00,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'product_id' => 1,
                'sku' => 'MBP14-M3-32-2TB',
                'processor' => 'Apple M3 Max',
                'ram' => '32GB',
                'storage' => '2TB SSD',
                'graphics_card' => 'M3 Max 30-core GPU',
                'display_size' => '14.2"',
                'resolution' => '3024x1964',
                'stock' => 5,
                'price' => 3199.00,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],

            // Dell XPS 13 variants (Product ID: 2)
            [
                'product_id' => 2,
                'sku' => 'XPS13-i5-8-256',
                'processor' => 'Intel Core i5-1335U',
                'ram' => '8GB',
                'storage' => '256GB SSD',
                'graphics_card' => 'Intel Iris Xe',
                'display_size' => '13.4"',
                'resolution' => '1920x1200',
                'stock' => 12,
                'price' => 999.00,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'product_id' => 2,
                'sku' => 'XPS13-i7-16-512',
                'processor' => 'Intel Core i7-1355U',
                'ram' => '16GB',
                'storage' => '512GB SSD',
                'graphics_card' => 'Intel Iris Xe',
                'display_size' => '13.4"',
                'resolution' => '1920x1200',
                'stock' => 7,
                'price' => 1299.00,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'product_id' => 2,
                'sku' => 'XPS13-i7-32-1TB',
                'processor' => 'Intel Core i7-1355U',
                'ram' => '32GB',
                'storage' => '1TB SSD',
                'graphics_card' => 'Intel Iris Xe',
                'display_size' => '13.4"',
                'resolution' => '3840x2400',
                'stock' => 5,
                'price' => 1699.00,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],

            // ThinkPad X1 Carbon variants (Product ID: 3)
            [
                'product_id' => 3,
                'sku' => 'TPX1-i5-16-512',
                'processor' => 'Intel Core i5-1345U',
                'ram' => '16GB',
                'storage' => '512GB SSD',
                'graphics_card' => 'Intel Iris Xe',
                'display_size' => '14"',
                'resolution' => '1920x1200',
                'stock' => 15,
                'price' => 1399.00,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'product_id' => 3,
                'sku' => 'TPX1-i7-32-1TB',
                'processor' => 'Intel Core i7-1365U',
                'ram' => '32GB',
                'storage' => '1TB SSD',
                'graphics_card' => 'Intel Iris Xe',
                'display_size' => '14"',
                'resolution' => '2560x1600',
                'stock' => 8,
                'price' => 1899.00,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],

            // ASUS ROG Zephyrus gaming variants (Product ID: 5)
            [
                'product_id' => 5,
                'sku' => 'ROG14-R7-16-1TB',
                'processor' => 'AMD Ryzen 7 7840HS',
                'ram' => '16GB',
                'storage' => '1TB SSD',
                'graphics_card' => 'NVIDIA RTX 4060',
                'display_size' => '14"',
                'resolution' => '2560x1600',
                'stock' => 6,
                'price' => 1799.00,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'product_id' => 5,
                'sku' => 'ROG14-R9-32-2TB',
                'processor' => 'AMD Ryzen 9 7940HS',
                'ram' => '32GB',
                'storage' => '2TB SSD',
                'graphics_card' => 'NVIDIA RTX 4070',
                'display_size' => '14"',
                'resolution' => '2560x1600',
                'stock' => 3,
                'price' => 2299.00,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'product_id' => 5,
                'sku' => 'ROG14-R9-64-4TB',
                'processor' => 'AMD Ryzen 9 7940HS',
                'ram' => '64GB',
                'storage' => '4TB SSD',
                'graphics_card' => 'NVIDIA RTX 4090',
                'display_size' => '14"',
                'resolution' => '2560x1600',
                'stock' => 2,
                'price' => 3299.00,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],

            // MacBook Air 15-inch variants (Product ID: 7)
            [
                'product_id' => 7,
                'sku' => 'MBA15-M2-8-256',
                'processor' => 'Apple M2',
                'ram' => '8GB',
                'storage' => '256GB SSD',
                'graphics_card' => 'M2 8-core GPU',
                'display_size' => '15.3"',
                'resolution' => '2880x1864',
                'stock' => 20,
                'price' => 1299.00,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'product_id' => 7,
                'sku' => 'MBA15-M2-16-512',
                'processor' => 'Apple M2',
                'ram' => '16GB',
                'storage' => '512GB SSD',
                'graphics_card' => 'M2 10-core GPU',
                'display_size' => '15.3"',
                'resolution' => '2880x1864',
                'stock' => 12,
                'price' => 1499.00,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ]
        ];

        DB::table('variants')->insert($variants);
    }
}